### ISSUE TITLE
I64 need signing methods

### ISSUE THREAD

**Issue by kermitv** [fishjd/HappyNewMoonWithReport#4]
https://github.com/fishjd/HappyNewMoonWithReport/blob/252389c82d5f3cf6dea221ab0b694b5b788ff387/src/main/java/happynewmoonwithreport/type/I64.java#L61

I64 needs the signed and unsigned methods similar to I32.  I took a look at it and couldn't figure out how to do it.  The I32 methods look like this:

    public S32 signedValue() {
        return new S32(value);
    }

    public U32 unsignedValue() {
        // java 8 and above.
        return new U32(Integer.toUnsignedLong(value));
    }

**Comment by fishjd** [comment]
Completed.  In Revision 252389c82d5f3cf6dea221ab0b694b5b788ff387
