### ISSUE TITLE
Questions about New Moon

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [fishjd/HappyNewMoonWithReport#7]
Heya, i just have a few questions about this aha!

1) How would i interact with Java functions in WASM code? Preferably in a way that doesn't require me to individually expose every class/function to the code

2) How much of this is implemented compared to wasmtime?

**Comment by fishjd** [comment]
1)  ### How would I interact with Java functions in WASM code? Preferably in a way that doesn't require me to individually expose every class/function to the code 


There are a couple of examples in the readme.md file.  
For example:  

```
Wasm wasm = new Wasm("HelloWorld.wasm");
System.out.println(wasm.exports().HelloWorld());
```

For a concrete example, see unit test:   

[WasmAdd32Test](https://github.com/fishjd/HappyNewMoonWithReport/blob/master/src/test/java/happynewmoonwithreport/loadFromWasm/WasmAdd32Test.java)

**Comment by fishjd** [comment]
### 2. How much of this is implemented compared to Wasmtime? 
 
I don't know much about Wasmtime.   At this point, a majority of the opcodes are implemented,  the big gap is the conditional opcodes such as 'if' are not implemented.   

Check the readme.md file for updates on completed opcodes.
